### ISSUE TITLE
Nothing Shows up

### ISSUE THREAD

**Issue by X0t0** [ratson/cordova-plugin-admob-free#152] opened 2018-01-19 11:33 UTC
Hello , i'm facing this problem for 2 days now
my ads not showing up at all , when i use this package name "io.ionic.starter" it's work 
but when i change it it doesn't, even if put a random package name like this : io.Unsdfsdfaqwz.starsdf
i tried like 16 package name but no one work , i though it's going to take time to showing up so i waited for 12 hours but still nothing shows up 
`    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 3.10.10
    OS                : Windows 10`

I tried THis 
`this.admobFree.banner.prepare().then(() => { console.log("fff") });`
and it's showing "fff" but i don't know why it's not showing ads

**Comment by rashnk** [comment] 2018-01-21 05:34
try` isTesting:true` in ad config

**Comment by erperejildo** [comment] 2018-02-12 15:23
Duplicated https://github.com/ratson/cordova-plugin-admob-free/issues/119

**Comment by erperejildo** [comment] 2018-03-02 13:48
@X0t0 can you close this duplicated ticket and comment on one above please?

**Comment by tominou** [comment] 2018-04-12 12:29
Duplicate of #119

**Closed by tominou** 2018-04-12 12:29 UTC
