### ISSUE TITLE
Black Screen IOS

### ISSUE THREAD

**Issue by touxstudio** [ratson/cordova-plugin-admob-free#34] opened 2016-12-06 11:39 UTC
Hi, I added this plugin using XDK installint via NPM but no luck.

I use C2 + XDK 

Is there a way to fix it? or some kind of guide?

Greetens

**Comment by code4youreal** [comment] 2016-12-06 11:46
For me works fine on iOS, I get black screen only if I use this plugin on Android.
I use C2 + XDK

**Comment by touxstudio** [comment] 2016-12-06 11:48
How do you export from C2? I tried with and without WkWebView, with and without Overlap, with test true and false. But no luck. Any advice please?

Greetens

**Comment by code4youreal** [comment] 2016-12-06 11:54
I use C2 r233 XDK 3641 
1. Do not check Minify script
2. Check WkWebView 

I use Overlap and test ad always false.

**Comment by code4youreal** [comment] 2016-12-06 11:55
You need to give in Intel XDK third party plugin cordova-plugin-admob-free

**Comment by ratson** [comment] 2016-12-06 15:24
@code4youreal Thanks for helping out. I personally don't use Intel XDK, would you like to be a collaborator to document integration?

**Comment by touxstudio** [comment] 2016-12-06 19:09
Thank you very code4youreal much it worked!

Is there any way to use it on Android too?

**Comment by code4youreal** [comment] 2016-12-06 19:26
This plugin do not works me on Android, because I get a black screen. 
Can you tell me which size do you use on iOS and Android?

**Comment by code4youreal** [comment] 2016-12-06 19:27
@ratson If I can then I help you, but I am beginner :D

**Comment by code4youreal** [comment] 2016-12-06 19:28
May be the problem is the Minify script I always check by Android but by iOS not.

**Comment by ratson** [comment] 2016-12-07 16:03
@code4youreal No worry, we all are beginner of something :)
Invitation sent 🚀 

I am closing this issue as it worked on iOS.
For the Android problem, let's refer to https://github.com/ratson/cordova-plugin-admob-free/issues/23

**Closed by ratson** 2016-12-07 16:03 UTC

**Comment by trgtgdk** [comment] 2019-08-12 12:12
> Hi, I added this plugin using XDK installint via NPM but no luck.
> 
> I use C2 + XDK
> 
> Is there a way to fix it? or some kind of guide?
> 
> Greetens
how install xdk via npm. can you help me ?
