### ISSUE TITLE
Getting error "Can't find variable: admob"

### ISSUE THREAD

**Issue by SharkyPT** [ratson/cordova-plugin-admob-free#181] opened 2018-03-15 14:01 UTC
Hi,

i'm testing this plugin in my app using PhoneGap.
When I use iOS i get the error "Can't find variable: admob". on initialization.
If I test using the browser (i know it does not wotk on browser), I do not get this error and the init works  ok.

On init i have something like:

` 

        admob.interstitial.config(
        {
            id: admobid.interstitial,
            isTesting: true,
            autoShow: false,
        });
        admob.interstitial.prepare();
    } `

And I have this error in iOS.
I 've already removed the plugin and add it again and also removed the platform and add it again.

Does anyone has a clue?

Thanks

**Comment by rlam3** [comment] 2018-03-28 19:55
@SharkyPT Any luck? I'm having a similar issue. Thanks.

**Comment by SharkyPT** [comment] 2018-03-29 16:30
No luck.

I will continue developing the App and will let the Ads to the end of the development.
Not sure if the plugin does not work inside Phonegap desktop and Phonegap App and if it works only after a proper build using Phonegap Build or the native android and iOS buils.

**Comment by rlam3** [comment] 2018-03-29 22:23
Do you mind sharing how you are importing admob? I'm getting the following error with my vue-js app
When I try to call upon the admob plugin.

Thanks! 

```
ReferenceError: admob is not defined
```

**Comment by tennist** [comment] 2018-06-11 17:23
It would not work in the emulator because it is dependent upon google play services and the android sdk.  Therefore you need to get it into either an android simulator or an actual device.  Please close this issue if the problem is resolved.

**Closed** 2018-06-11 18:08 UTC

**Comment by kshvsharma960** [comment] 2020-05-02 06:53
I am facing the same issue of admob is not defined error statement.
I am using actual device.
Please provide admob import detail on android.
Thanks
