### ISSUE TITLE
In IOS, showAd (false), it makes the banner goes blank, instead of disappearing

### ISSUE THREAD

**Issue by warcry2000** [ratson/cordova-plugin-admob-free#15] opened 2016-10-17 21:16 UTC
Hello,

In IOS when i used showAd(false) to hide the banner, it makes the banner goes blank, instead of disappearing.

This did not happen before. In version 1.0.5 working properly.

Many thank for work

**Comment by raulpopi** [comment] 2016-10-18 08:04
Does not happen every time, sometimes yes, sometimes no

**Comment by gfismtposb** [comment] 2016-10-21 08:10
i have the same problem, do you have any solution?
regards!!!

**Comment by vintage** [comment] 2016-10-22 13:21
Have you observed any pattern in making the space blank? I've been playing with it for few minutes, couldn't reproduce the issue using latest version of the library. And what does the "blank" mean? The banner becomes some "gray box" and still occupy the screen?

**Comment by raulpopi** [comment] 2016-10-22 14:49
Hello, this happens when I show and hidden the banner.
I do this in my application depending on the screen that the user visits.
Hiding the banner there are times when the banner is removed but the space it occupied is left White. Then on the screen that part of the banner remains white.
It is not disappear banner area.

This occurs in ipad.

Regards!!!

**Comment by vintage** [comment] 2016-10-22 15:01
What options are you using to initialize the plugin? Can you paste your initialization code here?

https://github.com/ratson/cordova-plugin-admob-free#3-set-options

**Comment by raulpopi** [comment] 2016-10-22 15:09
Helo, this:

AdMob.createBannerView( {
			publisherId: this.idBanner, 
			bannerAtTop: false,
			overlap: false, 
			offsetTopBar: false, 
			autoShow : true
		} );

**Comment by vintage** [comment] 2016-10-22 15:16
I didn't even know that you can pass options to the createBannerView instead of the setOptions, but after looking at the source code seems correct. Have you tried to first initialize the library:

```
AdMob.setOptions({
  publisherId: this.idBanner,
  bannerAtTop: false,
  overlap: false,
  offsetTopBar: false,
  isTesting: false,
  autoShow: true,
});
```

And after that calling the: `AdMob.createBannerView();`? Then once you navigate through pages call `AdMob. showAd(true)` or `AdMob. showAd(false)`. I can't say if it changes anything, but that's the way which I've used in my project. Additionally you can make a test and check if wrapping the code into setTimeout do the trick like:

```
setTimeout(function() { AdMob.showAd(true);}, 2000);
```

Are you using any framework for the app? Ionic for example?

**Comment by raulpopi** [comment] 2016-10-22 15:47
It will try to initialize.

I am using ionicframework.

If I tried to show and hide and with:
setTimeout (function () {AdMob.showAd (true);}, 2000);
Even hide several times if the second work.

I feel that because of the method
- (Void) resizeViews
Sometimes not successful.

thank you very much for your concern.

**Comment by vintage** [comment] 2016-10-22 20:02
Yes, it seems more than issue with the Ionic Framework than the AdMob library itself. I'm using the lib with the Ionic 2 and didn't have any problems at all, so it's probably related only to the Ionic 1. I'm not familiar with the Ionic 1, so I think better place to get help on this issue is to go directly to their issue tracker. Hope you will find solution for this!

**Comment by raulpopi** [comment] 2016-10-24 07:15
Hello thank you very much.

I tried it with 'setOptions' and neither is arranged.

When testing with an iPad 2 running, but with ipad 1 does not work.

I is that I'm not familiar with ionic 2, so do not know if it will be to use ionic 1.

I keep trying to see if I can find solution.

**Comment by ratson** [comment] 2017-01-15 16:54
I am closing this since v0.6 provides new set APIs.

**Closed by ratson** 2017-01-15 16:54 UTC
Labels: help wanted, iOS
