### ISSUE TITLE
Not working for iOS but it is for Android

### ISSUE THREAD

**Issue by UltimateGemini** [ratson/cordova-plugin-admob-free#157] opened 2018-01-30 20:41 UTC
I have my isTesting: false and provided my Id. The test ads work but not the live ones.

When I run the app on my iphone X or my iPad, the banner shows white and not clickable and also the Interstitial ad is not showing up either when a button is clicked. After looking in the console log i see these errors:
......../www/plugins/cordova-plugin-admob-free/www/admob.js.map : Failed to load resource: the server responded with a status of 404 (Not Found)

Error: Network Error       polyfills.js

I tried several thing: Removing the plugin and reinstalling it and  even removing iOS platform and reinstalling it but I still get the same error.

Its working for Android. I ran the app on my device and the live ads are working fine. The banner and the Interstitial ad. So i'm assuming it has to be with a problem on iOS, Can any one please help?

Package.json:
"ionic-native/admob-free": "^4.5.3",
"cordova-admob-sdk": "^0.13.1",
"cordova-plugin-admob-free": "^0.13.0",
"cordova-promise-polyfill": "0.0.2"

**Comment by Noel-F** [comment] 2018-01-31 21:15
So after seeing a few issues posted in this repo, i'm guessing this issue still hasn't been fixed within the plugin?

**Comment by PratikPagada** [comment] 2018-02-02 13:25
same issue

**Comment by rweligamage** [comment] 2018-02-04 07:58
same issue

**Comment by skekeu** [comment] 2018-02-17 13:34
Do your Ads still work in Android?
I have similar issue both on IOS and Android.

**Comment by Noel-F** [comment] 2018-02-18 18:31
For Android is does, but I removed the whole plugin.

**Comment by skekeu** [comment] 2018-02-19 00:07
I have it setup like:

```
showBannerAd(){    
    const bannerConfig: AdMobFreeBannerConfig = {
      id:'MY-AD-ID',
      autoShow: true,
      isTesting: false
    }
    this.adMob.banner.config(bannerConfig);
    this.adMob.banner.prepare().then(()=>{      
      console.log('show ad');
    }).catch(err => console.log(err));    
    
  }

```

Then I call it when platform is ready, like:
`this.showBannerAd();  ` 

But no matter what ... no ads displayed.
Am I missing something?

**Comment by aabdolla** [comment] 2018-03-11 19:31
Same issue here.

**Comment by checosele** [comment] 2018-03-13 21:05
Same issue, the first time that i opened the app on a device the advertisements were shown like test ads, but after the first time they don't appear, and how @aabdolla says there is a white bar where the advertisements have to be.

**Comment by skekeu** [comment] 2018-03-14 12:01
Guys,
Check on your admob accounts if you have informed your address at the payment page.
If you don't add your address there, the live ads won't be served.

That solved the issue for me.

**Comment by jensbrobak** [comment] 2018-03-15 18:17
I experience the same issue. I can't seem to add payment options yet, due to being a new AdMob account and I haven't reached the minimum earnings limit yet, so the adding payment option button is greyed out for me.

**Comment by Noel-F** [comment] 2018-03-15 19:59
@skekeu  

Just like @jensbrobak said, its not letting me since i have not met the minimum threshold. I'm not even using this plugin anymore. I removed it a few months ago when I was having the issue.

**Comment by aabdolla** [comment] 2018-03-17 09:39
@skekeu What are you using instead?

**Comment by skekeu** [comment] 2018-03-18 15:11
@aabdolla I'm using AdMob here. As I said before, after adding my payment address, solved the issue for me.

I did not have the minimum threshold, since my acc is new.
Check if you're adding the payment address at the right place.

**Comment by jensbrobak** [comment] 2018-03-19 06:18
@skekeu

You were absolutely right! - I managed to find payment options and changed it accordingly to match my company details exact, i already did this, but now I adjusted to fit 100% to my duns details and then the issue got resolved.

Thanks !!

**Comment by skekeu** [comment] 2018-03-19 10:00
@jensbrobak 

I'm glad you were able to solve it!

**Comment by arturoceballos** [comment] 2018-06-12 23:43
@jensbrobak How long did it take for Admob to start serving real ads to your app after updating your company details?

**Comment by jensbrobak** [comment] 2018-06-13 06:47
@arturoceballos I can’t say exactly but over the night after having adjusted the company details, then it suddenly started working as intended.

**Comment by neilrackett** [comment] 2018-06-27 21:19
I was seeing the same issue on iOS, with the following message output repeatedly into the console:

```
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
```

The solution was to disable _Limit Ad Tracking_ under `Settings > Privacy > Advertising`, which seems to limit more than just tracking in this instance.

**Comment by arturoceballos** [comment] 2018-09-05 23:48
@skekeu @jensbrobak Forgot to revisit this but that solved my problem too. Thanks, guys!

**Comment by manoharreddyporeddy** [comment] 2019-02-28 03:13
Ad unit >
Ad unit settings >
Implementation instructions >

You will see 2 IDs starting with "ca-app-pub-.xxxxxxxxxxxx"

one is ADMOB_APP_ID   -> use this while installing plugin
another is YOUR_AD_ID  -> this is correct for ads (above will give NETWORK ERROR for ads), now have "internal error", gave my address details also, will wait and try again after some time.

**Comment by manoharreddyporeddy** [comment] 2019-02-28 03:59
I solved and documented here::
https://github.com/manoharreddyporeddy/everyday-solutions/blob/master/display-ads-on-android-using-admob.js

**Comment by suathh** [comment] 2020-11-12 08:05
In my case it is working on Android and on iOS simulator but not on iOS device

**Closed** 2021-01-11 04:05 UTC
